### ISSUE TITLE
calling yaml.load() without Loader=... is deprecated

### ISSUE THREAD

**Issue by brainstorm** [vladsaveliev/NGS_Utils#2]
```
//miniconda/envs/umccrise/lib/python3.7/site-packages/ngs_utils/config.py:15: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details. 
  dic = load_yaml(open(fpath)) 
```

Same or similar fix as with https://github.com/umccr/hpc_utils/commit/22b0ef87a1bc334767f932c7dff712d8c3dc7893, I guess?

**Comment by pdiakumis** [comment]
Yep, still getting this warning in my test runs

**Comment by vladsavelyev** [comment]
Resolved it with https://github.com/vladsaveliev/NGS_Utils/commit/e9b7a476da42b652c59c48f64ed8271b5ddc418e but forgot to update here. Thanks guys!
