### ISSUE TITLE
Continuing development and making updates

### ISSUE THREAD

**Issue by scwatts** [vladsaveliev/NGS_Utils#5]
Hi Vlad, we're working on getting umccrise running with DRAGEN outputs and have found that some changes to `ngs_utils` will be required to do this. Specifically, updating `BaseBatch` attribute assignments ([link](https://github.com/vladsaveliev/NGS_Utils/blob/master/ngs_utils/Sample.py#L101-L102)) and implementing a `DragenBatch` method ([link](https://github.com/vladsaveliev/NGS_Utils/blob/master/ngs_utils/dragen.py#L196)). The approach to infer tumour/normal identity of samples for DRAGEN outputs will also need to be reworked - unfortunately the `-replay.json` file no longer contains the `RGSM` and `RGSM-tumor` key/values.

To continue development and to make these required changes, we would like to migrate the `ngs_util` repo to the UMCCR GH organisation account. Would you like to do this yourself? Otherwise we can fork and migrate that way. Let us know how you'd like to proceed.

Best, Stephen

/cc @ohofmann

**Comment by vladsavelyev** [comment]
Hi Stephen,

Would there be any issues in creating a fork? NGS_Utils is a dependency for other projects, not directly related to UMCCR. I don't mind transferring the ownership and creating a fork myself, but I think it'd be easier to do the other way around. Let me know what you think,

Vlad

**Comment by scwatts** [comment]
Thanks Vlad, we are certainly happy fork NGS_Utils to across to the UMCCR account ourselves. Regarding the changes that will be made, I can open a PR down the line if that might be useful - I'd ping you prior to submitting any PR so you can decide whether you'd like to merge the changes
